### PR TITLE
Add tech strategy document as Markdown

### PR DESCRIPTION
**Pull request by alexsoble**
# Notes 

+ See PBI 2975 and task 4732 in Azure DevOps.

### CODE REVIEW

**Comment by alexsoble** [comment]
@robjohnsonakgov is on vacation, so would you mind reviewing this instead @ecayer?

**Comment by alexsoble** [comment]
@ecayer Oh wait, you're not part of the AlaskaDHSS Organization yet!

**Comment by ecayer** [comment]
I believe @robjohnsonakgov  considered removing the Goal of getting off the mainframe from the top? This shouldn't hold up merging, just worth seeing if he wants to downplay that aspect. After conversation with Monica et al, it seemed to be clear that the mainframe isn't the only modernization goal, but also getting ARIES on sound footing AND responding to needs for new/changed functionality along the way.

**Comment by alexsoble** [comment]
@ecayer Look better now?

**Comment by robjohnsonakgov** [comment]
@alexsoble   Given that 10 team members voted for the stated Goal I think we should keep it in.

@ecayer current reading assignment leads to me believe we should change the word **Goal** to **Challenge**.  Thoughts?

I like the idea of an annual review date

**Comment by alexsoble** [comment]
@robjohnsonakgov No working on vacation! You've got to trust that your teammates will carry things forward while you're gone!! 😛 And you need to relax and recharge!

**Comment by alexsoble** [comment]
☝️Added back the "Goal" paragraph about the mainframe, changed it to "Challenge", and added a little table for actions and dates related to the document, with "Review by June 2019" as one of them. 

All of this can be expanded on and edited later since this is a living document — for example, if we want to change the "Review by" date or add other dates to the table. 

Since this has two ✅Approvals, I'm going to ship it now!

**Pull request merged**
