### PR TITLE
Update 2-QAP-draft.md

### PR DESCRIPTION
**Pull request by loriperko**
Update to WCAG 2.1

### CODE REVIEW

**Comment by waldoj** [comment]
This is a bold proposal! WCAG 2.1 was just approved a few weeks ago. I'm not even sure if testing tools support it yet, although if they don't they surely will soon. This PR proposes specifying WCAG 2.1, but not which level of WCAG 2.1: A, AA, or AAA. I recommend specifying the level of compliance, because otherwise vendors will be left deciding for themselves. I recommend adhering to AA. [Here's a guide to what's in A, AA, and AAA](http://davidmacd.com/blog/wcag-2.1-quick-guide.html). But to be clear, I recommend AA from a place of zero experience with WCAG 2.1, and based only on reviewing the rules within that guide.

Although I'd _prefer_ AAA, I think you're going to spook vendors. I think a good way to test out AAA would be, in the context of a procurement, to ask a vendor to take some time to evaluate how difficult it would be to adhere to AAA (both technically and in terms of their own knowledge).

**Comment by loriperko** [comment]
Hi Waldo, This was done at Nick's direction. Should the pull request be rejected so that a new pull request can specify "AA" level?

**Comment by nfaulknerAK** [comment]
wasn't AA what was specified in the previous versions? why wouldn't we just keep that?

**Comment by waldoj** [comment]
Ah, that's the good news — pull requests can be amended! In that way, it's possible for somebody to make a bold proposal like this, for discussion to ensue, the agreed-upon changes to be made, and then the consensus can be merged.

**Comment by waldoj** [comment]
@nfaulknerAK, yes, AA was specified in the prior version, but! AA brings with it new requirements in WCAG 2.1, so we're obliging vendors to do something slightly more difficult than in WCAG 2.0. I think that's a good thing, so that we can continually increase our WCAG requirements with the passage of time.

**Comment by nfaulknerAK** [comment]
I am aware that there are new requirements in 2.1. I still think its a good thing to move there.

**Comment by waldoj** [comment]
Oh, yeah, I'm definitely not arguing against it. :) I just figure we'll want to specify A, AA, or AAA.

**Pull request merged**
